// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNV8hRMCXA3DVAZiFdUIRbfBnT6eN58Qs',
    appId: '1:273122302794:web:dbd838e77f36f4d931ffb3',
    messagingSenderId: '273122302794',
    projectId: 'eduglobe-4d0eb',
    authDomain: 'eduglobe-4d0eb.firebaseapp.com',
    storageBucket: 'eduglobe-4d0eb.appspot.com',
    measurementId: 'G-Q35XD69K2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzlO518ZWLUYj4lJX6rIbXgfXYbmbx5lo',
    appId: '1:273122302794:android:39ef677fa9089c6031ffb3',
    messagingSenderId: '273122302794',
    projectId: 'eduglobe-4d0eb',
    storageBucket: 'eduglobe-4d0eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI7nuwcciwg3WVoFxaBmUl5eXntM8Qc6A',
    appId: '1:273122302794:ios:4aaddc31f656855731ffb3',
    messagingSenderId: '273122302794',
    projectId: 'eduglobe-4d0eb',
    storageBucket: 'eduglobe-4d0eb.appspot.com',
    iosBundleId: 'com.eduglobe.eduglobeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI7nuwcciwg3WVoFxaBmUl5eXntM8Qc6A',
    appId: '1:273122302794:ios:4aaddc31f656855731ffb3',
    messagingSenderId: '273122302794',
    projectId: 'eduglobe-4d0eb',
    storageBucket: 'eduglobe-4d0eb.appspot.com',
    iosBundleId: 'com.eduglobe.eduglobeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNV8hRMCXA3DVAZiFdUIRbfBnT6eN58Qs',
    appId: '1:273122302794:web:24c20ff042e0e0fe31ffb3',
    messagingSenderId: '273122302794',
    projectId: 'eduglobe-4d0eb',
    authDomain: 'eduglobe-4d0eb.firebaseapp.com',
    storageBucket: 'eduglobe-4d0eb.appspot.com',
    measurementId: 'G-SZGCV8RGBE',
  );
}
